git pp[platformio]
src_dir = .
include_dir = .

[env:proton]
platform = https://github.com/norandomtechie/platform-raspberrypi#feature/proton-picosdk-support
board = proton
framework = picosdk
debug_tool = picoprobe
upload_protocol = picoprobe
monitor_speed = 115200

build_src_filter =
    +<main.c>
    +<simon_says.c>
    +<timer_module.c>
    +<seg7.c>
    +<chardisp.c>
    +<chardisp.c>

build_flags =
    -O0
    -I${PROJECT_DIR}
    -I${PROJECT_DIR}/../common
