[platformio]
src_dir = .

[env:proton]
platform = https://github.com/norandomtechie/platform-raspberrypi#feature/proton-picosdk-support
board = proton
framework = picosdk
build_src_flags = -O0
build_flags = -I${PROJECT_DIR}/../common
build_src_filter = +<main.c> +<display.c> +<waves.c> +<inputs.c> +<led.c> +<game.c>
debug_tool = picoprobe
upload_protocol = picoprobe
monitor_speed = 115200
