[platformio]
src_dir = src
include_dir = src

[env:proton]
platform = https://github.com/norandomtechie/platform-raspberrypi#feature/proton-picosdk-support
board = proton
framework = picosdk
debug_tool = picoprobe
upload_protocol = picoprobe
monitor_speed = 115200
build_src_filter =
    +<main.c>
    +<blast_gauge.c>
    +<link.c>
    +<display.c>
    +<waves.c>
    +<inputs.c>
    +<led.c>
    +<game.c>
build_flags =
    -O0
    -I${PROJECT_DIR}/src
    -I${PROJECT_DIR}/../common