[platformio]
src_dir = .
include_dir = .

[env:proton]
platform = https://github.com/norandomtechie/platform-raspberrypi#feature/proton-picosdk-support
board = proton
framework = picosdk
debug_tool = picoprobe
upload_protocol = picoprobe
monitor_speed = 115200
build_src_filter =
    +<main.c>
    +<simon_says.c>
    +<chardisp.c>
    +<timer.c>
    +<button.c>
    +<display.c>
    +<font.S>
    +<peer_link.c>
build_flags =
    -O0
    -I${PROJECT_DIR}
