[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino

; Serial Monitor configuration
monitor_speed = 115200

; Optional but recommended: Speeds up the flashing process
upload_speed = 921600 

build_flags = 
    ; Forces the Arduino core to route standard "Serial" calls to the native USB-C port
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1